name: promote
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to promote'
        required: true
      core-version:
        description: 'The PatternFly core version'
        required: false
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_SECRET }}
      CORE_VERSION: ${{ github.event.inputs.core-version }}
      RELEASE_VERSION: ${{ github.event.inputs.version }}
      GH_TOKEN: ${{ secrets.DG_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.DG_GITHUB_TOKEN }} # needs to be an admin token to get around branch protection
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build dist
        run: yarn build
      - name: Deploy to NPM and Github
        run: .github/promote.sh
