name: promote
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:        
      - v2.*
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_SECRET }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Build dist
        run: yarn build
      - name: Deploy to NPM and Github
        run: .github/promote.sh
